#include<iostream>
#include <bits/stdc++.h>
#define fastio ios_base::sync_with_stdio(false);cin.tie(NULL);cout.tie(NULL)
using namespace std;
int main()
{
    fastio;
    long long t,n,m,i,j,k;
    cin>>t;
    while(t--)
    {
        cin>>n>>m;
        if((n*m)%2==1)
        {
            for(i=1;i<=n;i++)
            {
                for(j=1;j<=m;j++)
                {
                    if(i%2==1)
                    {
                        if(j%2==1)
                        {
                            cout<<"B";
                        }
                        else
                        {
                            cout<<"W";
                        }
                    }
                    else
                    {
                        if(j%2==1)
                        {
                            cout<<"W";
                        }
                        else
                        {
                            cout<<"B";
                        }
                    }
                }
                cout<<endl;
            }
        }
        else
        {
            for(i=1;i<=n;i++)
            {
                for(j=1;j<=m;j++)
                {
                    if(i==n)
                    {
                        for(k=1;k<=m-2;k++)
                        {
                            if(k%2==1)
                            {
                                cout<<"W";
                            }
                            else
                            {
                                cout<<"B";
                            }
                        }
                        cout<<"BB";
                        break;
                    }
                    if(i%2==1)
                    {
                        if(j%2==1)
                        {
                            cout<<"B";
                        }
                        else
                        {
                            cout<<"W";
                        }
                    }
                    else
                    {
                        if(j%2==1)
                        {
                            cout<<"W";
                        }
                        else
                        {
                            cout<<"B";
                        }
                    }
                }
                cout<<endl;
            }
        }
    }
    return 0;
}
